# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tictactoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setMouseTracking(True)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.lineh1 = QtWidgets.QFrame(self.centralwidget)
        self.lineh1.setEnabled(False)
        self.lineh1.setGeometry(QtCore.QRect(25, 200, 750, 3))
        self.lineh1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineh1.setLineWidth(1)
        self.lineh1.setMidLineWidth(5)
        self.lineh1.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh1.setObjectName("lineh1")
        self.lineh2 = QtWidgets.QFrame(self.centralwidget)
        self.lineh2.setEnabled(False)
        self.lineh2.setGeometry(QtCore.QRect(25, 400, 750, 3))
        self.lineh2.setStyleSheet("")
        self.lineh2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lineh2.setMidLineWidth(5)
        self.lineh2.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineh2.setObjectName("lineh2")
        self.linev1 = QtWidgets.QFrame(self.centralwidget)
        self.linev1.setEnabled(False)
        self.linev1.setGeometry(QtCore.QRect(265, 25, 3, 550))
        self.linev1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.linev1.setMidLineWidth(5)
        self.linev1.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev1.setObjectName("linev1")
        self.linev2 = QtWidgets.QFrame(self.centralwidget)
        self.linev2.setEnabled(False)
        self.linev2.setGeometry(QtCore.QRect(534, 25, 3, 550))
        self.linev2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.linev2.setMidLineWidth(5)
        self.linev2.setFrameShape(QtWidgets.QFrame.VLine)
        self.linev2.setObjectName("linev2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic Tac Toe"))
